// Code generated by MockGen. DO NOT EDIT.
// Source: permit.go
//
// Generated by this command:
//
//	mockgen -source=permit.go -destination=../../../test/mocks/gomock/homeassistant/clientpermit/permit.go
//
// Package mock_clientpermit is a generated GoMock package.
package mock_clientpermit

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockdiscovery is a mock of discovery interface.
type Mockdiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockdiscoveryMockRecorder
}

// MockdiscoveryMockRecorder is the mock recorder for Mockdiscovery.
type MockdiscoveryMockRecorder struct {
	mock *Mockdiscovery
}

// NewMockdiscovery creates a new mock instance.
func NewMockdiscovery(ctrl *gomock.Controller) *Mockdiscovery {
	mock := &Mockdiscovery{ctrl: ctrl}
	mock.recorder = &MockdiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdiscovery) EXPECT() *MockdiscoveryMockRecorder {
	return m.recorder
}

// SendDiscoverySwitch mocks base method.
func (m *Mockdiscovery) SendDiscoverySwitch(commandTopic, stateTopic, deviceName, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDiscoverySwitch", commandTopic, stateTopic, deviceName, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDiscoverySwitch indicates an expected call of SendDiscoverySwitch.
func (mr *MockdiscoveryMockRecorder) SendDiscoverySwitch(commandTopic, stateTopic, deviceName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDiscoverySwitch", reflect.TypeOf((*Mockdiscovery)(nil).SendDiscoverySwitch), commandTopic, stateTopic, deviceName, name)
}

// MockaccessUpdate is a mock of accessUpdate interface.
type MockaccessUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockaccessUpdateMockRecorder
}

// MockaccessUpdateMockRecorder is the mock recorder for MockaccessUpdate.
type MockaccessUpdateMockRecorder struct {
	mock *MockaccessUpdate
}

// NewMockaccessUpdate creates a new mock instance.
func NewMockaccessUpdate(ctrl *gomock.Controller) *MockaccessUpdate {
	mock := &MockaccessUpdate{ctrl: ctrl}
	mock.recorder = &MockaccessUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccessUpdate) EXPECT() *MockaccessUpdateMockRecorder {
	return m.recorder
}

// SetPermit mocks base method.
func (m *MockaccessUpdate) SetPermit(mac string, permit bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermit", mac, permit)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermit indicates an expected call of SetPermit.
func (mr *MockaccessUpdateMockRecorder) SetPermit(mac, permit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermit", reflect.TypeOf((*MockaccessUpdate)(nil).SetPermit), mac, permit)
}

// Mockmqtt is a mock of mqtt interface.
type Mockmqtt struct {
	ctrl     *gomock.Controller
	recorder *MockmqttMockRecorder
}

// MockmqttMockRecorder is the mock recorder for Mockmqtt.
type MockmqttMockRecorder struct {
	mock *Mockmqtt
}

// NewMockmqtt creates a new mock instance.
func NewMockmqtt(ctrl *gomock.Controller) *Mockmqtt {
	mock := &Mockmqtt{ctrl: ctrl}
	mock.recorder = &MockmqttMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmqtt) EXPECT() *MockmqttMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *Mockmqtt) SendMessage(topic, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendMessage", topic, message)
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockmqttMockRecorder) SendMessage(topic, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*Mockmqtt)(nil).SendMessage), topic, message)
}

// Subscribe mocks base method.
func (m *Mockmqtt) Subscribe(topic string) chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", topic)
	ret0, _ := ret[0].(chan string)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockmqttMockRecorder) Subscribe(topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*Mockmqtt)(nil).Subscribe), topic)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *Mocklogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockloggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mocklogger)(nil).Error), varargs...)
}
